#include <iostream>
#include <fstream>
#include <vector>
#include <stdexcept>
#include <random>
#include <cmath>
#include <limits>
#include <string>
#include <cctype>
#include <cstring>
#include <filesystem>
#include <algorithm>
#include <atomic>

#include "neural_core/core_utils.hpp"
#include "neural_core/data.hpp"
#include "neural_core/matrix.hpp"
#include "neural_core/model.hpp"
#include "neural_core/rng.hpp"
#include "neural_core/scatter_plot.hpp"

using std::cout;
using std::is_trivially_copyable_v;
using std::istream;
using std::ifstream;
using std::ostream;
using std::ofstream;
using std::streamsize;
using std::ios;
using std::vector;
using std::unique_ptr;
using std::runtime_error;
using std::size_t;
using std::string;
using std::atomic;
using std::numeric_limits;
using std::mt19937;
using std::normal_distribution;
using std::uniform_real_distribution;
using std::uniform_int_distribution;
using std::seed_seq;
using std::random_device;
using std::exception;
using std::memory_order_relaxed;
using std::memory_order_release;
using std::memory_order_acquire;
using std::swap;
using std::move;
using std::memcmp;
using std::min;
using std::max;
using std::round;
using std::sqrt;
using std::abs;
using std::sin;
using std::cos;
using std::acos;
using std::exp;
using std::log;
using std::isfinite;
using std::transform;
using std::tolower;
using std::make_unique;

#include "neural_core/activations.hpp"
#include "neural_core/layers.hpp"
#include "neural_core/losses.hpp"
#include "neural_core/optimizers.hpp"
#include "neural_core/accuracy.hpp"
